name: Run Python Scripts Automatically in Pairs

on:
  schedule:
    - cron: '0 13 * * *'  # 台灣時間13:00 (GitHub Actions 使用 UTC 時間)

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        script:
          - 'code/hkg.py'
          - 'code/hkgbusi.py'   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install selenium requests pandas

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install --reinstall -y chromium-chromedriver
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true

    - name: Check Chrome and ChromeDriver versions
      run: |
        google-chrome --version || chromium-browser --version
        chromedriver --version

    - name: Ensure data directory exists
      run: mkdir -p data && ls -lh data/

    - name: Run script
      run: |
        set -x
        python ${{ matrix.script }}

    - name: Debug CSV File Creation
      run: |
        echo "Checking data directory..."
        ls -lh data/ || echo "No files in data/"
        echo "Current directory contents:"
        ls -lh
        echo "Python scripts directory contents:"
        ls -lh code/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: flight-data
        path: data/*.csv
        if-no-files-found: warn  # 如果沒有找到 CSV，不要直接報錯

